# Generated by Django 4.1.1 on 2022-10-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_remove_women_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['time_create'], 'verbose_name': 'Известная женщина', 'verbose_name_plural': 'Известные женщины'},
        ),
    ]
